### ISSUE TITLE
Event name with - gives error, example save-item

### ISSUE THREAD

**Issue by wdebusschere** [symphonycms/symphonycms#2854]
Affected Symphony version(s) : 3.0.0
PHP version(s) : 7.1
OS(es) :

Symphony Fatal Error: syntax error, unexpected '-', expecting '{'

Please follow the guideline for security bug disclosure https://github.com/symphonycms/symphony-2/wiki/Security-Bug-Disclosure

**Comment by nitriques** [comment]
Thanks, I will try to reproduce

**Comment by nitriques** [comment]
I just tested 2.7.x and it does not seem to be affected

**Comment by wdebusschere** [comment]
3.0.0 issue

**Comment by nitriques** [comment]
Can you test the latest 3.0.x branch please ?

**Comment by nitriques** [comment]
Ok will test more thanks.

**Comment by nitriques** [comment]
@wdebusschere This fixes it in 2.7.x: https://github.com/symphonycms/symphony-2/commit/cc375c55546f6d00f13034adbd356c39949110af  It will be in 3.0.x when it is rebased.

**Comment by wdebusschere** [comment]
@nitriques This was working for us in 2.7.x

**Comment by nitriques** [comment]
@wdebusschere Ok great, I'll let you know when 3.0.x will be rebased.
